name: 'Substring'
description: 'Substring an input value'
inputs:
  value:  # id of input
    description: 'What to substring'
    required: true
  start:
    description: 'The position where to start the extraction. First character is at index 0.'
    required: true
    default: '0'
  length:
    description: 'The number of characters to extract. If omitted, it extracts the rest of the string.'
    required: false # value length by default
outputs:
  result: 
    description: 'A new String, containing the extracted part of the text. If length is 0 or negative, an empty string is returned.'
runs:
  using: 'node12'
  main: 'index.js'
